name: 'Increment variable'

author: kroese

description: 'Action to increment a repository variable.'

branding:
  icon: "plus"
  color: "gray-dark"

inputs:
  name:
    description: Name
    required: true

  repository:
    description: Repository name
    default: false
    required: false

  owner:
    description: Owner of repository
    default: false
    required: false

  org:
    description: Flag for organization
    default: false
    required: false

  token:
    description: Repository access token
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
