name: 'Set Secret'

author: kroese

description: 'Action to set secrets in a repository'

branding:
  icon: lock
  color: gray-dark

inputs:
  name:
    description: Secret name
    required: true

  value:
    description: Secret value
    required: true

  repository:
    description: Repository name
    default: false
    required: false

  owner:
    description: Owner of repository
    default: false
    required: false

  org:
    description: Flag to use organization
    default: false
    required: false

  token:
    description: Repository access token
    required: true

runs:
  using: 'node16'
  main: 'index.js'
