name: Build

on: 
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - run: npm install
    - name: Test the action
      uses: ./.
      with:
        name: 'MY_SECRET'
        value: 'Lorem ipsun dolor simit'
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - run: echo ${{secrets.MY_SECRET }} | sed 's/./& /g'
  
  build:
    needs: test
    name: Build bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com 
          git checkout -b release/${{ secrets.MINOR }}
      - name: Test and Build
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          npm i -g @vercel/ncc
          npm install --production
          npm run build
      - name: Clean files
        run: |
          rm .gitignore
          rm -Rf node_modules/
          rm -Rf .github
          rm index.js
      - name: Git Create Branch release/${{ secrets.MINOR }} 
        run: |
          git add .
          git commit -m "Auto commit from Github Actions #${{ github.run_id }}"
          git push origin release/${{ secrets.MINOR }} -f

  deploy:
    name: Deploy Bundle
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Publish new version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com 
          git tag -fa v${{ secrets.MINOR }} -m "Update v${{ secrets.MINOR }} tag"
          git push origin v${{ secrets.MINOR }} --force
      -
        name: Increment minor version
        run: echo "NEW_MINOR=$((${{ secrets.MINOR }}+1))" >> $GITHUB_ENV
      -
       name: Update minor version
       uses: kroese/set-secret@v1
       with:
         name: 'MINOR'
         value: ${{ env.NEW_MINOR }}
         repository: ${{ github.repository }}
         token: ${{ secrets.REPO_ACCESS_TOKEN }}
