name: Test

on: 
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      -
        name: Test increment
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Test increment by 2
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          amount: 2
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Test decrement by 2
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          amount: -2
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
