name: Test

on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: npm install

    - name: Test the action
      uses: ./.
      with:
        name: 'MY_SECRET_NAME'
        value: 'Lorem ipsun dolor simit'
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
  
    - run: tst="${{ secrets.MY_SECRET_NAME }}" && echo $tst

