name: Test

on: 
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      -
        name: Set variable    
        uses: action-pack/set-variable@v1
        with:
          name: 'TEST'
          value: '1'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}    
      -
        name: Test increment
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Test increment by 2
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          amount: 2
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Test decrement by 2
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          amount: -4
          token: ${{ secrets.REPO_ACCESS_TOKEN }}    
      -
        name: Set variable    
        uses: action-pack/set-variable@v1
        with:
          name: 'TEST'
          value: '09'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}    
      -
        name: Test increment
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Test increment by 2
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          amount: 2
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Test decrement by 2
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          amount: -4
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Set variable    
        uses: action-pack/set-variable@v1
        with:
          name: 'TEST'
          value: '0.5.09'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}    
      -
        name: Test increment
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Test increment by 2
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          amount: 2
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Test decrement by 2
        uses: action-pack/increment@v2
        with:
          name: 'TEST'
          amount: -4
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
